services:
  scanner:
    command: python -m tgtg_scanner -c /cfg/config.ini
    image: derhenning/tgtg:latest-alpine           ## pre build image from docker hub
    # image: tgtg-scanner:latest                   ## locally build image
    # build:                                       ## build image with compose
    #   context: .
    #   dockerfile: docker/Dockerfile.alpine
    environment:
    # # # Configuration via environment variables.
    # # # Basic example using Telegram notifications
    # # # For more options and details visit https://github.com/Der-Henning/tgtg/wiki/Configuration

    # - TGTG_USERNAME=uberutubr@gmail.com
    # - SLEEP_TIME=60
    - TZ=America/New_York
    - LOCALE=en_US
    # - SCHEDULE_CRON="* 8-22 * * *"

    # - TELEGRAM=true
    # - TELEGRAM_TOKEN=6675160664:AAEx2xsV1jSSBqd-l9HFRBezYInxZgeHWIY
    # - TELEGRAM_CHAT_IDS=-1001760599338
    # - TELEGRAM_TIMEOUT=60
    # - TELEGRAM_BODY='*${{display_name}}*\n*Available*: ${{items_available}}\n*Rating*: ${{rating}}\n*Price*: ${{price}}\n*Pickup*: ${{pickupdate}}\n'

    volumes:
    - tokens:/tokens             ## volume to save TGTG credentials to reuse on next start up and avoid login mail
    # - ./tgtg_scanner:/usr/local/lib/python3.11/site-packages/tgtg_scanner
    - ./cfg/config.ini:/cfg/config.ini
volumes:
  tokens:
